#!/bin/bash
# Case conditions

read -p "Please enter your age: " age

case $age in
[0-4])
	echo "Too young for school."
	;;
5)
	echo "Go to kindergarten."
	;;
[6-9]|1[0-8])
	grade=$(( age - 5 ))
	echo "Go to $grade grade."
	;;
*)
	echo "Go to adult education."
	;;
esac

case $age in
1[8,9]|[2-9][0-9])
	echo "Right to vote: Yes"
	;;
*)
	echo "Right to vote: No" 
	;;
esac


